### ISSUE TITLE
Fluxo da tela de login do aluno

### ISSUE THREAD

**Issue by terenciani** [OAllanFernando/ArmariosIFPR#19]
Se tem armário emprestado, exibe somente a tabela de empréstimos para ele efetuar a devolução
senão exibe somente a tela de empréstimo, para ele efetuar o empréstimo.
O histórico de reservas pode ser visualizado em ambas as telas

Aumentar o tamanho dos botões.

**Comment by OAllanFernando** [comment]
Implementado na branch 19 - fluxo de login
