### ISSUE TITLE
Trocar palavra "reserva" por "empréstimo" em todo o sistema

### ISSUE THREAD

**Issue by terenciani** [OAllanFernando/ArmariosIFPR#3]

**Comment by OAllanFernando** [comment]
Visualmente alterado para emprestimo. Já internamente ainda me refiro como reserva. 
Como não faz diferença ao usuário deixei como reserva, mas se for necessário altero o resto. 
Conclui a issue caso concorde :)

**Comment by terenciani** [comment]
Estou fazendo as refatorações para o panel de controle e aproveitei e já fiz a alteração.
Não é interessante que tenhamos divergências entre as informações visuais e o código escrito.
